spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/climax;DB_CLOSE_DELAY=-1
    username: climax
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop